routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\StudentProfileController;
use App\Http\Controllers\GuardianProfileController;
use App\Http\Controllers\LocalizationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route::group(['middleware' => 'localization'], function(){
	
// })

Route::get('setlocale/{lang}', [LocalizationController:: class, 'index'])->name('language');

Route::get('/',	[PagesController::class, 'dashboard'])->name('dashboard');
Route::get('dashboard',	[PagesController::class, 'dashboard'])->name('dashboard');
Route::get('students', [PagesController::class, 'students'])->name('students');


Route::get('guardians', [PagesController::class, 'guardians'])->name('guardians');
Route::group(['prefix' => 'student', 'as' => 'student.'], function(){
	Route::post('new', [StudentProfileController::class, 'createStudent'])->name('create');
	Route::get('new', [PagesController::class, 'studentForm'])->name('new');
	Route::get('{id}', [PagesController::class, 'studentViewForm'])->name('view');
	Route::put('update', [StudentProfileController::class, 'updateStudent'])->name('update');
	Route::delete('destroy', [StudentProfileController::class, 'deleteStudent'])->name('destroy');
	Route::group(['prefix' => 'guardian', 'as' => 'guardian.'], function(){
		Route::post('save-guardian', [GuardianProfileController::class, 'createGuardian'])->name('create');
		Route::put('save-guardian', [GuardianProfileController::class, 'updateGuardian'])->name('update');
	});
});

resources/views/partials/head.blade.php
<meta charset="utf-8" />
<title>@lang('global.app.title.full') | {{ $data['title'] }}</title>
<meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
<meta content="" name="description" />
<meta content="" name="author" />
<meta name="csrf-token" content="{{ csrf_token() }}">

<!-- ================== BEGIN BASE CSS STYLE ================== -->
<link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
<link href="{{ asset('plugins/jquery-ui/themes/base/minified/jquery-ui.min.css') }}" rel="stylesheet" />
<link href="{{ asset('plugins/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet" />
<link href="{{ asset('plugins/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet" />
<link href="{{ asset('css/animate.min.css') }}" rel="stylesheet" />
<link href="{{ asset('css/style.min.css') }}" rel="stylesheet" />
<link href="{{ asset('css/style-responsive.min.css') }}" rel="stylesheet" />
<link href="{{ asset('css/theme/default.css') }}" rel="stylesheet" id="theme" />

<!-- Begin custom CSS -->
<link href="{{ asset('css/custom.css') }}" rel="stylesheet" />
<!-- End custom CSS -->

<!-- ================== BEGIN BASE JS ================== -->
<script src="{{ asset('plugins/pace/pace.min.js') }}"></script>
<!-- ================== END BASE JS ================== -->

@if(\Route::currentRouteName() == 'student.new' || \Route::currentRouteName() == 'student.view')
<link href="{{ asset('plugins/bootstrap-datepicker/css/datepicker.css') }}" rel="stylesheet" />
<link href="{{ asset('plugins/bootstrap-datepicker/css/datepicker3.css') }}" rel="stylesheet" />
<link href="{{ asset('plugins/ionRangeSlider/css/ion.rangeSlider.css') }}" rel="stylesheet" />
<link href="{{ asset('plugins/ionRangeSlider/css/ion.rangeSlider.skinNice.css') }}" rel="stylesheet" />
<link href="{{ asset('plugins/bootstrap-colorpicker/css/bootstrap-colorpicker.min.css') }}" rel="stylesheet" />
<link href="{{ asset('plugins/bootstrap-timepicker/css/bootstrap-timepicker.min.css') }}" rel="stylesheet" />
<link href="{{ asset('plugins/password-indicator/css/password-indicator.css') }}" rel="stylesheet" />
<link href="{{ asset('plugins/bootstrap-combobox/css/bootstrap-combobox.css') }}" rel="stylesheet" />
<link href="{{ asset('plugins/bootstrap-select/bootstrap-select.min.css') }}" rel="stylesheet" />
<link href="{{ asset('plugins/bootstrap-tagsinput/bootstrap-tagsinput.css') }}" rel="stylesheet" />
<link href="{{ asset('plugins/jquery-tag-it/css/jquery.tagit.css') }}" rel="stylesheet" />
<link href="{{ asset('plugins/bootstrap-daterangepicker/daterangepicker-bs3.css') }}" rel="stylesheet" />
<link href="{{ asset('plugins/select2/dist/css/select2.min.css') }}" rel="stylesheet" />
<link href="{{ asset('plugins/bootstrap-eonasdan-datetimepicker/build/css/bootstrap-datetimepicker.min.css') }}" rel="stylesheet" />
@endif
<!-- ================== END BASE CSS STYLE ================== -->

@if(\Route::currentRouteName() == 'dashboard')
<!-- ================== BEGIN PAGE LEVEL STYLE ================== -->
<link href="{{ asset('plugins/jquery-jvectormap/jquery-jvectormap-1.2.2.css') }}" rel="stylesheet" />
<link href="{{ asset('plugins/bootstrap-datepicker/css/datepicker.css') }}" rel="stylesheet" />
<link href="{{ asset('plugins/bootstrap-datepicker/css/datepicker3.css') }}" rel="stylesheet" />
<link href="{{ asset('plugins/gritter/css/jquery.gritter.css') }}" rel="stylesheet" />
<!-- ================== END PAGE LEVEL STYLE ================== -->
@endif

resources/views/partials/headernavbar.blade.php
<!-- begin container-fluid -->
<div class="container-fluid">
	<!-- begin mobile sidebar expand / collapse button -->
	<div class="navbar-header">
		<a href="{{ route('dashboard') }}" class="navbar-brand"><span class="navbar-logo"></span> {{ __('global.app.title.short') }}</a>
		<button type="button" class="navbar-toggle" data-click="sidebar-toggled">
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
	</div>
	<!-- end mobile sidebar expand / collapse button -->
	
	<!-- begin header navigation right -->
	<ul class="nav navbar-nav navbar-right">
		<li>
			<form class="navbar-form full-width">
				<div class="form-group">
					<input type="text" class="form-control" placeholder="{{ __('global.app.search.enter_key_word') }}" />
					<button type="submit" class="btn btn-search"><i class="fa fa-search"></i></button>
				</div>
			</form>
		</li>
		<li class="dropdown navbar-user">
			<a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
				<span class="hidden-xs">{{ __('global.app.language.pick') }}</span> <b class="caret"></b>
			</a>
			<ul class="dropdown-menu animated fadeInLeft">
				<li class="arrow"></li>
				<li><a href="{{ route('language', 'en') }}"><img class='country-flag' src="{{ asset('img/country-flags/usa.png') }}" alt="{{ __('global.app.language.english-us') }}" /> {{ __('global.app.language.english-us') }}</a></li>
				<li class="divider"></li>
				<li><a href="{{ route('language', 'swa') }}"><img class='country-flag' src="{{ asset('img/country-flags/kenya.png') }}" alt="{{ __('global.app.language.kiswahili-ken') }}" /> {{ __('global.app.language.kiswahili-ken') }}</a></li>
			</ul>
		</li>
		<li class="dropdown">
			<ul class="dropdown-menu media-list pull-right animated fadeInDown">
                <li class="dropdown-header">Notifications (5)</li>
                <li class="">
                    <a href="javascript:;">
                        <div class="media-left"><i class="fa fa-bug media-object bg-red"></i></div>
                        <div class="media-body">
                            
                        </div>
                    </a>
                </li>
            </ul>
        </li>
	</ul>
	<!-- end header navigation right -->
</div>
<!-- end container-fluid -->

resources/views/partials/scripts.blade.php
<!-- ================== BEGIN BASE JS ================== -->
<script src="{{ asset('plugins/jquery/jquery-1.9.1.min.js') }}"></script>
<script src="{{ asset('plugins/jquery/jquery-migrate-1.1.0.min.js') }}"></script>
<script src="{{ asset('plugins/jquery-ui/ui/minified/jquery-ui.min.js') }}"></script>
<script src="{{ asset('plugins/bootstrap/js/bootstrap.min.js') }}"></script>
<!--[if lt IE 9]>
	<script src="assets/crossbrowserjs/html5shiv.js"></script>
	<script src="assets/crossbrowserjs/respond.min.js"></script>
	<script src="assets/crossbrowserjs/excanvas.min.js"></script>
<![endif]-->
<script src="{{ asset('plugins/slimscroll/jquery.slimscroll.min.js') }}"></script>
<script src="{{ asset('plugins/jquery-cookie/jquery.cookie.js') }}"></script>
<!-- ================== END BASE JS ================== -->

@if(\Route::currentRouteName() == 'dashboard')	
<!-- ================== BEGIN PAGE LEVEL JS ================== -->
<script src="{{ asset('plugins/gritter/js/jquery.gritter.js') }}"></script>
<script src="{{ asset('plugins/flot/jquery.flot.min.js') }}"></script>
<script src="{{ asset('plugins/flot/jquery.flot.time.min.js') }}"></script>
<script src="{{ asset('plugins/flot/jquery.flot.resize.min.js') }}"></script>
<script src="{{ asset('plugins/flot/jquery.flot.pie.min.js') }}"></script>
<script src="{{ asset('plugins/sparkline/jquery.sparkline.js') }}"></script>
<script src="{{ asset('plugins/jquery-jvectormap/jquery-jvectormap-1.2.2.min.js') }}"></script>
<script src="{{ asset('plugins/jquery-jvectormap/jquery-jvectormap-world-mill-en.js') }}"></script>
<script src="{{ asset('plugins/bootstrap-datepicker/js/bootstrap-datepicker.js') }}"></script>
<script src="{{ asset('js/dashboard.min.js') }}"></script>
<!-- ================== END PAGE LEVEL JS ================== -->
@endif

@if(\Route::currentRouteName() == 'student.new' || \Route::currentRouteName() == 'student.view')
<script src="{{ asset('plugins/bootstrap-datepicker/js/bootstrap-datepicker.js') }}"></script>
<script src="{{ asset('plugins/ionRangeSlider/js/ion-rangeSlider/ion.rangeSlider.min.js') }}"></script>
<script src="{{ asset('plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js') }}"></script>
<script src="{{ asset('plugins/masked-input/masked-input.min.js') }}"></script>
<script src="{{ asset('plugins/bootstrap-timepicker/js/bootstrap-timepicker.min.js') }}"></script>
<script src="{{ asset('plugins/password-indicator/js/password-indicator.js') }}"></script>
<script src="{{ asset('plugins/bootstrap-combobox/js/bootstrap-combobox.js') }}"></script>
<script src="{{ asset('plugins/bootstrap-select/bootstrap-select.min.js') }}"></script>
<script src="{{ asset('plugins/bootstrap-tagsinput/bootstrap-tagsinput.min.js') }}"></script>
<script src="{{ asset('plugins/bootstrap-tagsinput/bootstrap-tagsinput-typeahead.js') }}"></script>
<script src="{{ asset('plugins/jquery-tag-it/js/tag-it.min.js') }}"></script>
<script src="{{ asset('plugins/bootstrap-daterangepicker/moment.js') }}"></script>
<script src="{{ asset('plugins/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
<script src="{{ asset('plugins/select2/dist/js/select2.min.js') }}"></script>
<script src="{{ asset('plugins/bootstrap-eonasdan-datetimepicker/build/js/bootstrap-datetimepicker.min.js') }}"></script>
<script src="{{ asset('js/form-plugins.demo.min.js') }}"></script>
@endif
<!-- ================== BEGIN PAGE LEVEL JS ================== -->
<script src="{{ asset('js/apps.min.js') }}"></script>
<!-- ================== END PAGE LEVEL JS ================== -->
<script type="text/javascript">
	$.ajaxSetup({
	    headers: {
	        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
	    }
	});
</script>
<script>
	$(document).ready(function() {
		App.init();
		@if(\Route::currentRouteName() == 'student.new' || \Route::currentRouteName() == 'student.view')
		FormPlugins.init();
		@endif
	});
</script>

<script>
  $(document).ready(function(){
      $('button.destroy_student').on('click', function(){
        	$.ajax({
        		url: "{{ route('student.destroy') }}",
        		type: "post",
        		cache: false,
        		data:{'_method' : 'DELETE', id: $(this).data("id")},
        		success: function(results){
        			results = JSON.parse(results);
        			if(results.statusCode === 200){
        				$(".panel-body").html('<div class="alert alert-success">Record deleted</div>');
        			}
        		}
        	});
      });
  });
</script>

<script type="text/javascript" src="{{ asset('js/custom.js') }}"></script>

resources/views/partials/sidebar.blade.php
<!-- begin sidebar scrollbar -->
<div data-scrollbar="true" data-height="100%">
	<!-- begin sidebar nav -->
	<ul class="nav">
		<li class="{{ request()->routeIs('dashboard') ? 'active' : '' }}" }}><a href="{{ route('dashboard') }}"><i class="fa fa-dashboard"></i> <span>{{ __('global.dashboard') }}</span></a></li>
		<li class="has-sub {{ request()->routeIs('student*') ? 'active' : '' }}">
		    <a href="javascript:;">
			    <b class="caret pull-right"></b>
		        <i class="fa fa-child"></i>
		        <span>{{ trans_choice('global.user.students.student', 2) }}</span>
		    </a>
			<ul class="sub-menu">
				<li class="{{ request()->routeIs('students') ? 'active' : '' }}"><a href="{{ route('students') }}">{{ trans_choice('global.user.students.student', 2) }}</a></li>
				<li class="{{ request()->routeIs('student.new') ? 'active' : '' }}"><a href="{{ route('student.new') }}">{{ trans_choice('global.user.students.new', 1) }}</a></li>
			</ul>
		</li>
		<li class="{{ request()->routeIs('guardians*') ? 'active' : '' }}"><a href="{{ route('guardians') }}"><i class="fa fa-home"></i> <span>{{ trans_choice('global.user.guardians.guardian', 1) }}</span></a></li>
	</ul>
	<!-- end sidebar nav -->
</div>
<!-- end sidebar scrollbar -->