routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\StudentProfileController;
use App\Http\Controllers\GuardianProfileController;
use App\Http\Controllers\LocalizationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route::group(['middleware' => 'localization'], function(){
	
// })

Route::get('setlocale/{lang}', [LocalizationController:: class, 'index'])->name('language');

Route::get('/',	[PagesController::class, 'dashboard'])->name('dashboard');
Route::get('dashboard',	[PagesController::class, 'dashboard'])->name('dashboard');
Route::get('students', [PagesController::class, 'students'])->name('students');


Route::get('guardians', [PagesController::class, 'guardians'])->name('guardians');
Route::group(['prefix' => 'student', 'as' => 'student.'], function(){
	Route::post('new', [StudentProfileController::class, 'createStudent'])->name('create');
	Route::get('new', [PagesController::class, 'studentForm'])->name('new');
	Route::get('{id}', [PagesController::class, 'studentViewForm'])->name('view');
	Route::put('update', [StudentProfileController::class, 'updateStudent'])->name('update');
	Route::delete('destroy', [StudentProfileController::class, 'deleteStudent'])->name('destroy');
	Route::group(['prefix' => 'guardian', 'as' => 'guardian.'], function(){
		Route::post('save-guardian', [GuardianProfileController::class, 'createGuardian'])->name('create');
		Route::put('save-guardian', [GuardianProfileController::class, 'updateGuardian'])->name('update');
	});
});

resources/views/partials/students/all.blade.php
<table class="table">
	<thead>
		<tr>
			<th>#</th>
			<th>{{ __('global.user.names') }}</th>
			<th>{{ __('global.user.students.admission_number') }}</th>
			<th>{{ __('global.user.sex') }}</th>
			<th>{{ __('global.user.date_of_birth') }}</th>
			<th>{{ trans_choice('global.actions.action', 2)}}</th>
		</tr>
	</thead>
	<tbody>
		@forelse($data['students'] as $key => $student)
		<tr>
			<td>{{ ++$key }}</td>
			<td>{{ $student->first_name }} {{ $student->last_name }}</td>
			<td>{{ $student->admission_number }}</td>
			<td>{{ $student->sex }}</td>
			<td>{{ $student->date_of_birth }}</td>
			<td>
				<div class="col-lg-3 col-md-3 col-xs-6">
				<a class="btn btn-success btn-xs" href="{{ route('student.view', $student->id) }}">{{ __('global.actions.view') }}</a>
				</div>
				<div class="col-lg-3 col-md-3 col-xs-6">
					<button class="btn btn-xs btn-danger destroy_student" data-id="{{ $student->id }}">{{ __('global.actions.delete') }}</button>
				</div>
			</td>
		</tr>
		@empty
		<tr>
			<td colspan="6">{{ __('global.messages.no_data') }}</td>
		</tr>
		@endforelse			
	</tbody>
</table>